dataabc/weiboSpider

config_sample.json
validator.py
writer.py

修复了上次 pull request 里的两个 bug:
1. 正确的 csv 表头顺序 
2. 支持并行多种 write mode

fix bugs mentioned in multi-file mode

---

weiboSpider.py

由windows自带编辑器设置user_id_list.txt可能会使文本内容前被自动加上一个\ufeff字符，从而使程序出问题，将utf-8替换为utf-8-sig可忽略该字符，也保证程序对utf-8编码的检测顺利

修复由windows自带编辑器设置user_id_list.txt的一些问题

---

.gitignore
weibo_spider/writer/mysql_writer.py

爬取微博过程中出现若干个 pymysql.err.DataError: (1406, "Data too long for column 'content' at row 1")

将 MySQL 库建表语句的正文长度上限提高到 5000

---

weibo_spider/config_sample.json
weibo_spider/config_util.py
weibo_spider/spider.py
weibo_spider/writer/__init__.py
weibo_spider/writer/kafka_writer.py

由于我想做一个实时爬取微博消息主动推送的东西，所以增加了一个KafkaWriter，可以向消息队列写入数据，实时推送，配置内容如下：
```json
{
"kafka_config": {
"bootstrap-server": "127.0.0.1:9092", #kafka地址, 集群用逗号分隔
"weibo_topics": ["spider_weibo"], # 推送微博消息的topic
"user_topics": ["spider_weibo"]  # 推送用户个人信息的topic
}
}
```
个人能力有限，不足之处还望提出来，联系邮件: windlively@live.cn，望采纳。

feature: 增加kafka writer，支持向kafka实时推送爬取的数据

---

weibo_spider/spider.py

兼容现有的模式下，支持就像「.txt」那样混合的user_id_list
```json
{
"user_id_list": ["1729370543", {
"id": "1669879400",
"since_date": "2020-11-01 18:15"
}],
}
```
这样使得程序的调用的时候会更灵活一点
- 另外清理了一下commit历史 合并成一个
- 对于非dict保持去重的功能

feat: user_id_list在config.json支持混合的模式

---

weibo_spider/parser/util.py

Windows 在配置 GENERATE_TEST_DATA 为 True 时执行程序会报错：
'gbk' codec can't encode character 'xxxx' in position xxxxxx: illegal multibyte sequence
原因是在 Windows 系统上，程序会将内容从 utf-8 编码转换为 gbk 编码，再写入文件。编码转换过程出现错误。

fix(test data): 修复 Windows 系统下写入 Test Data 文件报错的问题

---

.gitignore

默认配置文件将 SQLite 数据库文件名称配置为 weibo.db。应该忽略程序根据默认配置生成的文件。

chore(gitignore): 忽略使用 SQLite 时生成的 weibo.db

---

weibo_spider/downloader/__init__.py
weibo_spider/downloader/img_downloader.py
weibo_spider/downloader/origin_picture_downloader.py
weibo_spider/downloader/retweet_picture_downloader.py
weibo_spider/spider.py

feat(downloader): 添加下载原微博图片的功能

---

docs/FAQ.md

使用 https://weibo.cn/%s/info 就可以获取。
如果使用 https://weibo.cn/%s/profile 会进入自己发送和转发的微博列表，程序无法获取到数据，导致出现以下错误：
list index out of range
.....
'NoneType' object has no attribute 'nickname'

docs(faq): 获取自己的微博不需要修改 info_parser.py

---

weibo_spider/parser/comment_parser.py
weibo_spider/parser/page_parser.py
weibo_spider/parser/util.py

feat(page_parser): 添加获取长微博视频链接的功能

---

weibo_spider/parser/info_parser.py
weibo_spider/parser/util.py

fix: when uid==1 then crash

---

README.md

bibtex 格式参考自：
https://github.com/tensorflow/models#citing-tensorflow-model-garden
Author 列表来自：
https://github.com/dataabc/weiboSpider/graphs/contributors
有一个小问题是很多contributor没有实名，所以只列了他们的Github用户名。
暂时还没有想到特别好的解决办法。
Year 当前设置为了上次重构和切换python版本（2=>3）的时间。

Add a bibtex item for the weiboSpider repo.

---

docs/settings.md
weibo_spider/config_sample.json
weibo_spider/writer/mongo_writer.py

另外：authenticate()方法在PyMongo3.6版本就已弃用，本人不是很确定使用authenticate()的必要性，这一部分可能还需要后续改动。
PyMongo changlog如下：
> Deprecated authenticate(). Authenticating multiple users conflicts with support for logical sessions in MongoDB 3.6. To authenticate as multiple users, create multiple instances of [MongoClient](https://pymongo.readthedocs.io/en/stable/api/pymongo/mongo_client.html#pymongo.mongo_client.MongoClient).

更新MongoDB设置及相关文档

---

weibo_spider/parser/page_parser.py

Fix #518.
主要是两个修改：
1. 通过搜索“头条文章”，我们发现有两种可能的文本“发布了头条文章”或“我发表了头条文章”
2. 通过查看相应的链接，我们发现头条文章现在的url形式为 https://weibo.com/ttarticle/
已使用以下user id做了测试：
1. 6045161833 
NgvSY9mW7,我发表了头条文章:《《小城人物志（2）》》 《小城人物志（2）》  ,https://weibo.com/ttarticle/p/show?id=2309404939358200529130 ,无,无,True,无,无,2023-08-27 14:36,李小李的iPhone 11,0,0,0
2. 1955190431
Ng2CODhDi,发布了头条文章：《關於不實報道的重要申明澄清》  關於不實報道的重要申明澄清  ,https://weibo.com/ttarticle/p/show?id=2309404938233426608435 ,无,无,True,无,无,2023-08-24 12:07,微博 weibo.com,42,15,10

Fix the crawling of toutiao article urls.

---

weibo_spider/parser/comment_parser.py
weibo_spider/parser/util.py

修复了：无法正确获取需要“展开”的长文微博
优化了：如果长文微博中有换行则保留格式。长文微博文本中的<br>标签被替换为\n
```
def get_long_weibo(self):
"""获取长原创微博"""
try:
for i in range(5):
self.selector = handle_html(self.cookie, self.url)
if self.selector is not None:
info_div = self.selector.xpath("//div[@class='c' and @id='M_']")[0]
info_span = info_div.xpath("//span[@class='ctt']")[0]
html_string = etree.tostring(info_span, encoding='unicode', method='html')
html_string = html_string.replace('<br>', '\n')
new_content = fromstring(html_string).text_content()
new_content = re.sub(r'\n+', '\n', new_content)
weibo_content = handle_garbled(new_content)
if weibo_content is not None:
return weibo_content
sleep(random.randint(6, 10))
except Exception:
logger.exception(u'网络出错')
```
结果示例：
```
{
"id": "Obuk4oIaU",
"user_id": "",
"content": …
```

issues_bug_574 无法匹配获取微博长文，尝试修复

---

docs/settings.md
weibo_spider/config_sample.json
weibo_spider/config_util.py
weibo_spider/parser/comment_parser.py
weibo_spider/spider.py
weibo_spider/writer/__init__.py
weibo_spider/writer/post_writer.py

通过添加配置实现通过POST方式将数据推送到自定义接口
```
"write_mode": ["post"],
```
```
"post_config": {
"api_url": "https://api.example.com/weibo/post",
"api_token": ""
}
```

issues_feature_post_api_576 实现通过POST方式将数据推送到自定义接口

---

weibo_spider/parser/page_parser.py

handle_html 函数返回 Element 或者 None，`page_parser.py` 没有处理 None 的情况
```py
'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
File "C:\Users\zw\miniconda3\lib\site-packages\weibo_spider\spider.py", line 178, in get_weibo_info
weibos, self.weibo_id_list, to_continue = PageParser(
File "C:\Users\zw\miniconda3\lib\site-packages\weibo_spider\parser\page_parser.py", line 47, in __init__
info = self.selector.xpath("//div[@class='c']")
AttributeError: 'NoneType' object has no attribute 'xpath'
```

解决 'NoneType' object has no attribute 'xpath'

---

requirements.txt
weibo_spider/config_util.py
weibo_spider/spider.py

current approach:
user has to go to the website manually to grab the cookie
requirements: 
user has to be logged in to weibo.cn on the Chrome browser 
solution: 
grabs the cookie from the browser and adds it to the cookie section in config.json when the crawler is ran for the first time
future:
if the cookie becomes invalid we can run this functionality

feat: automated cookie grabbing for config.json (must be logged in on chrome)

---

weibo_spider/config_util.py
weibo_spider/spider.py

Issue
- previous commit only adds the cookie to the config.json when the program is ran for the first time, this will require manual intervention if anything happens to the cookie.  
Solution
- updated cookie workflow to check if the user is logged in 
- the cookie updates if the user is logged in and the new cookie is not the same as the current one
- moved the function call to when the config is being loaded into the program
Concerns
- takes a few seconds after logging in for retrieval to work properly
- user now has to be logged in Weibo on Chrome for this program to run

update: improved retrieval of cookies workflow

---

requirements.txt
weibo_spider/config_util.py

并且修复以下问题:
这里的 cookie 有可能不含 "MLOGIN" 这个 key，例如此时我未登录的 cookie 为：
```
{'SUB': '_2A25I0S7kDeRhGeVP6lET9yjJzjmIHXVrry4srDV6PUJbktANLWXAkW1NTU8PBZ0pWcKBCiA1prnv4RhE1j-P_CWd', 'SUBP': '0033WrSXqPxfM725Ws9jqgMF55529P9D9WhxVcpPFHOwH1VA0_OSa3CL5JpX5KzhUgL.FoepeKeES0qfSK-2dJLoI7R_TPW0IPxQUPiDMcX_TBtt'}
```
在这种情况下会抛异常：
```
Check for cookie failed: 'MLOGIN'
'MLOGIN'
Traceback (most recent call last):
File "/Users/songzy/weiboSpider/weibo_spider/spider.py", line 387, in main
config = _get_config()
File "/Users/songzy/weiboSpider/weibo_spider/spider.py", line 376, in _get_config
config_util.check_cookie(config_path)
File "/Users/songzy/weiboSpider/weibo_spider/config_util.py", line 211, in check_cookie
if cookie["MLOGIN"] == '0':
KeyError: 'MLOGIN'
```
可修正为
```
if cookie.get("MLOGIN", '0') == '0':
```

Use the pypi index version of browser_cookie3 in requirements.txt
